name: Node.js testing CI

# Trigger CI on push or pull request to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    # 'steps' represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      # Designed for automated environments like CI. It uses 'package-lock.json'.
      run: npm ci

    - name: Run tests
      # Allow tests to fail
      run: npm run test:coverage || echo "Tests failed, continuing..."
      continue-on-error: true

    - name: List directory contents
      run: |
        echo "List all files in the project directory:"
        ls -R
        echo "List all files in the coverage directory:"
        ls ./coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        files: ./coverage/clover.xml
        flags: tests
        name: codecov-umbrella # Optional: Custom name for the upload displayed on Codecov
